"""MkDocs build hook: publish verification evidence with the site.

Before every build, generate ``docs/traceability-matrix.md`` from the system of
record: run the acceptance suite (Allure evidence), reconcile it against the
declared design inputs (``rdm story verify``), and render the traceability
matrix. The docs site then *carries* the current evidence instead of linking to
artifacts that expire.

Best-effort by design: in an environment without the test tooling (e.g. a
docs-only install) the matrix template still renders — with its built-in
"no verification data" notice — so ``mkdocs build --strict`` never breaks.
"""

from __future__ import annotations

import contextlib
import io
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "docs" / "traceability-matrix.md"

BANNER = (
    "<!-- GENERATED by docs/_hooks/evidence.py at build time — do not edit or commit. -->\n\n"
    "!!! note \"Generated verification evidence\"\n"
    "    Produced from a live acceptance-suite run at {stamp} during the docs\n"
    "    build. The source of truth is the record itself: the design documents\n"
    "    under `dhf/`, the executed Allure results, and git history.\n\n"
)


def _generate() -> str:
    from rdm.main import cli

    data_files: list[str] = []
    try:
        subprocess.run(
            [sys.executable, "-m", "pytest", "tests/acceptance",
             "--alluredir", "dhf/allure-results", "-q"],
            cwd=ROOT, check=True, capture_output=True, timeout=600,
        )
        verify_rc = cli([
            "story", "verify", "--dhf", "dhf",
            "--allure-results", "dhf/allure-results",
            "-o", "dhf/data/verification.yml",
        ])
        if verify_rc == 0:
            data_files = ["dhf/data/verification.yml"]
    except Exception:
        data_files = []  # render the template's no-data notice instead

    rendered = io.StringIO()
    with contextlib.redirect_stdout(rendered):
        cli(["render", "dhf/documents/traceability_matrix.md", "dhf/config.yml", *data_files])
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    # Drop the template's frontmatter block; MkDocs gets the banner + body.
    body = rendered.getvalue()
    if body.lstrip().startswith("---"):
        body = body.split("---", 2)[2].lstrip("\n")
    return BANNER.format(stamp=stamp) + body


def on_pre_build(config) -> None:
    import os

    os.chdir(ROOT)  # rdm commands and pytest paths are repo-root relative
    content = _generate()
    # Write only on change so `mkdocs serve` does not rebuild in a loop
    # (a content-equal write is skipped; the timestamp alone is not a change
    # worth a rebuild cycle).
    if OUTPUT.exists():
        old = OUTPUT.read_text(encoding="utf-8")
        if old.split("\n", 6)[6:] == content.split("\n", 6)[6:]:
            return
    OUTPUT.write_text(content, encoding="utf-8")
